// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhPnzAeBJsls0ZYvE42eef9-X5-86v2Ds',
    appId: '1:831467395917:web:c1ab6bcac539666739f504',
    messagingSenderId: '831467395917',
    projectId: 'micollinsapp',
    authDomain: 'micollinsapp.firebaseapp.com',
    storageBucket: 'micollinsapp.firebasestorage.app',
    measurementId: 'G-LYV0P6HRZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Op-lSfNmmGPzKvsdImneVuL1jzYfNoM',
    appId: '1:831467395917:android:b942aae8311ee6eb39f504',
    messagingSenderId: '831467395917',
    projectId: 'micollinsapp',
    storageBucket: 'micollinsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzjfzH6FGUBTDt2lPT5PlzTfb50iHkowA',
    appId: '1:831467395917:ios:14f7ec80a2cdfa1839f504',
    messagingSenderId: '831467395917',
    projectId: 'micollinsapp',
    storageBucket: 'micollinsapp.firebasestorage.app',
    iosClientId: '831467395917-o7cfqn3735eaop36s8kqv1vq6rjjrnbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.micollinsDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzjfzH6FGUBTDt2lPT5PlzTfb50iHkowA',
    appId: '1:831467395917:ios:14f7ec80a2cdfa1839f504',
    messagingSenderId: '831467395917',
    projectId: 'micollinsapp',
    storageBucket: 'micollinsapp.firebasestorage.app',
    iosClientId: '831467395917-o7cfqn3735eaop36s8kqv1vq6rjjrnbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.micollinsDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhPnzAeBJsls0ZYvE42eef9-X5-86v2Ds',
    appId: '1:831467395917:web:82824cc2d139c13339f504',
    messagingSenderId: '831467395917',
    projectId: 'micollinsapp',
    authDomain: 'micollinsapp.firebaseapp.com',
    storageBucket: 'micollinsapp.firebasestorage.app',
    measurementId: 'G-LCSW2X1YBC',
  );
}
